[package]
name = "dread_locker"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.1"
file = "1.1.2"

[features] 
default = ["windows"]
linux = []
windows = []
